version: "3.4"
services:
  run:
    build:
      context: .
      target: run
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app

  air:
    build:
      context: .
      target: air
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app

  lint:
    build:
      context: .
      target: lint
    volumes:
      - .:/go/src/app

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./database:/docker-entrypoint-initdb.d
